import type {
  Campaign,
  GsaProfile,
  KpiPoint,
  LinkedinSource,
  LinkedinImportRequest,
  LinkedinPostPreview,
  NewsCategory,
  NewsPost,
  Notification,
  Tender,
  TenderApplication,
} from "./types";

export const tenders: Tender[] = [
  {
    id: "tnd-eur-001",
    title: "Central Europe GSA representation",
    airline: "AeroBridge Cargo",
    regions: ["Germany", "Austria", "Switzerland"],
    lanes: "FRA, MUC, VIE to DXB, DOH, SIN",
    annualTonnage: 18400,
    productMix: "General cargo, pharma, express",
    deadline: "May 24, 2026",
    status: "open",
    expectedStart: "Q3 2026",
    requirements: ["GDP-certified pharma desk", "24/7 booking coverage", "Monthly route-level KPI reporting"],
  },
  {
    id: "tnd-iberia-002",
    title: "Iberia belly capacity sales launch",
    airline: "NorthStar Airways",
    regions: ["Spain", "Portugal"],
    lanes: "MAD, BCN, LIS to JFK, ORD, MEX",
    annualTonnage: 11200,
    productMix: "Perishables, e-commerce, mail",
    deadline: "Jun 3, 2026",
    status: "open",
    expectedStart: "Q4 2026",
    requirements: ["Perishables sales coverage", "IATA CASS experience", "Named key accounts pipeline"],
  },
  {
    id: "tnd-nordics-003",
    title: "Nordics freighter sales RFP",
    airline: "PolarLine Cargo",
    regions: ["Sweden", "Norway", "Denmark", "Finland"],
    lanes: "ARN, OSL, CPH, HEL to ICN, PVG, NRT",
    annualTonnage: 15600,
    productMix: "Tech, seafood, high value",
    deadline: "Jun 18, 2026",
    status: "open",
    expectedStart: "Q1 2027",
    requirements: ["Seafood handling track record", "ULD planning capability", "Local language sales teams"],
  },
];

export const gsaProfiles: GsaProfile[] = [
  {
    id: "gsa-bluewing",
    name: "BlueWing Cargo Solutions",
    headquarters: "Frankfurt, Germany",
    coverage: ["DACH", "Benelux", "CEE"],
    certifications: ["IATA", "GDP", "ISO 9001"],
    cargoFocus: "Pharma, automotive, express",
    networkScore: 92,
    financialScore: 88,
    complianceScore: 96,
    winRate: 41,
    summary: "Enterprise GSA with strong airline transition playbooks, dense DACH shipper relationships, and a pharma-focused operations desk.",
  },
  {
    id: "gsa-atlantic",
    name: "Atlantic AirCargo Partners",
    headquarters: "Madrid, Spain",
    coverage: ["Iberia", "Morocco", "France"],
    certifications: ["IATA", "CASS", "CEIV Fresh"],
    cargoFocus: "Perishables, mail, transatlantic belly cargo",
    networkScore: 86,
    financialScore: 83,
    complianceScore: 89,
    winRate: 36,
    summary: "Commercially aggressive Iberia specialist with strong perishables and passenger belly capacity sales programs.",
  },
  {
    id: "gsa-nordic",
    name: "NordicLift Aviation Services",
    headquarters: "Copenhagen, Denmark",
    coverage: ["Nordics", "Baltics"],
    certifications: ["IATA", "ISO 14001"],
    cargoFocus: "Seafood, technology, high-value cargo",
    networkScore: 89,
    financialScore: 81,
    complianceScore: 91,
    winRate: 33,
    summary: "Regional specialist with deep seafood exporter relationships and a proven launch history for Asian capacity.",
  },
];

export const applications: TenderApplication[] = [
  {
    id: "app-001",
    tenderId: "tnd-eur-001",
    gsaId: "gsa-bluewing",
    gsaName: "BlueWing Cargo Solutions",
    commercialScore: 91,
    networkScore: 94,
    complianceScore: 96,
    proposedCommission: "5.8% base + 1.2% accelerator",
    status: "shortlisted",
    submittedAt: "Apr 21, 2026",
  },
  {
    id: "app-002",
    tenderId: "tnd-eur-001",
    gsaId: "gsa-atlantic",
    gsaName: "Atlantic AirCargo Partners",
    commercialScore: 84,
    networkScore: 78,
    complianceScore: 88,
    proposedCommission: "5.1% fixed",
    status: "pending",
    submittedAt: "Apr 22, 2026",
  },
  {
    id: "app-003",
    tenderId: "tnd-nordics-003",
    gsaId: "gsa-nordic",
    gsaName: "NordicLift Aviation Services",
    commercialScore: 87,
    networkScore: 91,
    complianceScore: 90,
    proposedCommission: "6.0% base + launch bonus",
    status: "accepted",
    submittedAt: "Apr 19, 2026",
  },
];

export const kpiSeries: KpiPoint[] = [
  { month: "Apr", date: "2025-04", revenue: 695000, loadfactor: 56, yield: 1.93 },
  { month: "May", date: "2025-05", revenue: 710000, loadfactor: 57, yield: 1.95 },
  { month: "Jun", date: "2025-06", revenue: 730000, loadfactor: 58, yield: 1.97 },
  { month: "Jul", date: "2025-07", revenue: 755000, loadfactor: 59, yield: 1.99 },
  { month: "Aug", date: "2025-08", revenue: 780000, loadfactor: 60, yield: 2.02 },
  { month: "Sep", date: "2025-09", revenue: 795000, loadfactor: 61, yield: 2.04 },
  { month: "Oct", date: "2025-10", revenue: 805000, loadfactor: 62, yield: 2.06 },
  { month: "Nov", date: "2025-11", revenue: 820000, loadfactor: 61, yield: 2.08 },
  { month: "Dec", date: "2025-12", revenue: 910000, loadfactor: 65, yield: 2.14 },
  { month: "Jan", date: "2026-01", revenue: 970000, loadfactor: 68, yield: 2.21 },
  { month: "Feb", date: "2026-02", revenue: 1020000, loadfactor: 71, yield: 2.24 },
  { month: "Mar", date: "2026-03", revenue: 1180000, loadfactor: 74, yield: 2.31 },
  { month: "Apr", date: "2026-04", revenue: 1260000, loadfactor: 77, yield: 2.38 },
];

export const newsCategories: NewsCategory[] = [
  "GSA opportunity",
  "airline expansion",
  "new route",
  "cargo capacity",
  "tender/RFP",
  "partnership",
];

export const newsPosts: NewsPost[] = [
  {
    id: "news-001",
    title: "AeroBridge Cargo evaluates DACH sales representation for new Middle East lanes",
    source: "LinkedIn: AeroBridge Cargo",
    category: "GSA opportunity",
    market: "DACH",
    publishedAt: "Apr 27, 2026",
    summary: "Carrier signaled a commercial build-out tied to Frankfurt and Munich departures, with pharma and express cargo named as focus verticals.",
    confidence: 92,
  },
  {
    id: "news-002",
    title: "NorthStar Airways adds Madrid and Lisbon widebody rotations",
    source: "LinkedIn: NorthStar Airways",
    category: "airline expansion",
    market: "Iberia",
    publishedAt: "Apr 26, 2026",
    summary: "New long-haul passenger capacity creates belly cargo availability across JFK, ORD, and Mexico City lanes from Q4.",
    confidence: 87,
  },
  {
    id: "news-003",
    title: "PolarLine Cargo opens seafood-focused RFP for Nordic export markets",
    source: "LinkedIn: PolarLine Cargo",
    category: "tender/RFP",
    market: "Nordics",
    publishedAt: "Apr 25, 2026",
    summary: "The post references a formal partner selection process for freighter capacity serving Asia-bound seafood and technology shippers.",
    confidence: 94,
  },
  {
    id: "news-004",
    title: "SkyHarbor signs handling partnership at Vienna for temperature-controlled cargo",
    source: "LinkedIn: SkyHarbor Logistics",
    category: "partnership",
    market: "Central Europe",
    publishedAt: "Apr 24, 2026",
    summary: "The agreement adds cool-chain handling capacity and may support new airline commercial programs in Austria.",
    confidence: 78,
  },
];

export const linkedinSources: LinkedinSource[] = [
  {
    id: "src-001",
    name: "Oman Air Cargo",
    url: "https://www.linkedin.com/showcase/omanair-cargo/posts/?feedView=all",
    category: "cargo capacity",
    status: "active",
    lastImport: "Apr 27, 2026 08:10",
  },
  {
    id: "src-002",
    name: "Etihad Cargo",
    url: "https://www.linkedin.com/showcase/etihad-cargo/posts/?feedView=all",
    category: "airline expansion",
    status: "active",
    lastImport: "Apr 26, 2026 16:45",
  },
  {
    id: "src-003",
    name: "PolarLine Cargo",
    url: "https://www.linkedin.com/company/polarline-cargo/posts/?feedView=all",
    category: "tender/RFP",
    status: "paused",
    lastImport: "Apr 25, 2026 11:20",
  },
];

export const linkedinImportDefaults: LinkedinImportRequest = {
  includeQuotePosts: false,
  includeReposts: false,
  maxComments: 0,
  maxPosts: 50,
  maxReactions: 0,
  postNestedComments: false,
  postNestedReactions: false,
  postedLimit: "any",
  scrapeComments: false,
  scrapeReactions: false,
  targetUrls: linkedinSources.filter((source) => source.status === "active").map((source) => source.url),
};

export const linkedinPostPreview: LinkedinPostPreview = {
  id: "7329207003942125568",
  linkedinUrl:
    "https://www.linkedin.com/posts/williamhgates_how-better-data-helped-us-cut-child-mortality-activity-7329207003942125568-_gfJ",
  authorName: "Bill Gates",
  authorUrl: "https://www.linkedin.com/in/williamhgates",
  content:
    "The leading causes of childhood death reveal a stark truth: Many could be prevented, and children in poor countries die from them far more often than those in wealthy ones.",
  postedAt: "2025-05-16T18:11:59.821Z",
  media: [
    {
      type: "document",
      title: "How better data helped us cut child mortality in half",
      url: "https://media.licdn.com/dms/document/media/v2/D561FAQGPMwZUeWRF4w/feedshare-document-pdf-analyzed",
    },
    {
      type: "image",
      title: "Document cover page",
      url: "https://media.licdn.com/dms/image/v2/D561FAQGPMwZUeWRF4w/feedshare-document-cover-images_1920",
      width: 1921,
      height: 1243,
    },
  ],
};

export const notifications: Notification[] = [
  {
    id: "ntf-001",
    title: "Shortlist update",
    body: "BlueWing Cargo Solutions moved to shortlist for Central Europe representation.",
    time: "18 min ago",
    status: "unread",
  },
  {
    id: "ntf-002",
    title: "Tender deadline reminder",
    body: "Nordics freighter sales RFP closes in 51 days.",
    time: "2 hr ago",
    status: "unread",
  },
  {
    id: "ntf-003",
    title: "New opportunity match",
    body: "NorthStar Iberia launch matches your perishables coverage profile.",
    time: "Yesterday",
    status: "read",
  },
];

export const airlineCampaigns: Campaign[] = [
  {
    id: "cmp-001",
    title: "FRA–DXB Frequency Increase — Summer 2026",
    type: "route_announcement",
    status: "published",
    author: "AeroBridge Cargo",
    authorRole: "airline",
    channels: ["platform"],
    audience: "All GSA partners",
    body: "We are pleased to announce an increase in freighter frequency on the Frankfurt–Dubai corridor starting 1 June 2026. Weekly departures will rise from 5 to 7, adding approximately 140 tonnes of available capacity per week. Priority product allocation applies to pharma and express categories. Please update your sales pipeline accordingly and reach out to your account manager for AWB block allocation.",
    bannerImageUrl: "https://images.unsplash.com/photo-1521727857535-28d2047314ac?auto=format&fit=crop&w=1200&q=80",
    publishedAt: "Apr 28, 2026",
    createdAt: "Apr 25, 2026",
    reach: 312,
    engagement: 48,
  },
  {
    id: "cmp-002",
    title: "Q2 Pharma Capacity: Priority Lane Activation",
    type: "capacity_highlight",
    status: "published",
    author: "AeroBridge Cargo",
    authorRole: "airline",
    channels: ["platform"],
    audience: "All GSA partners",
    body: "AeroBridge Cargo is activating dedicated pharma capacity across BRU, ZRH, and MUC for Q2 2026. All lanes are IATA CEIV-certified and feature real-time temperature monitoring. Minimum booking lead time is 48 hours. GDP documentation must accompany all shipments. Capacity is allocated on a first-come basis — contact your regional desk to secure slots.",
    airlineLogoUrl: "/globe.svg",
    publishedAt: "Apr 15, 2026",
    createdAt: "Apr 12, 2026",
    reach: 284,
    engagement: 61,
  },
  {
    id: "cmp-003",
    title: "Summer 2026 Network Expansion — Preview",
    type: "news_update",
    status: "scheduled",
    author: "AeroBridge Cargo",
    authorRole: "airline",
    channels: ["platform"],
    audience: "All GSA partners",
    body: "AeroBridge Cargo will announce three new freighter destinations for the Summer 2026 schedule: Nairobi (NBO), Hanoi (HAN), and Bogotá (BOG). Detailed capacity, frequency, and product mix information will follow. GSA partners with existing coverage in these markets are encouraged to express interest ahead of formal tender publication.",
    scheduledFor: "May 10, 2026",
    createdAt: "Apr 30, 2026",
  },
  {
    id: "cmp-004",
    title: "DACH E-Commerce Launch — Partner Activation",
    type: "promotion",
    status: "draft",
    author: "AeroBridge Cargo",
    authorRole: "airline",
    channels: ["platform"],
    audience: "DACH GSA partners",
    body: "We are preparing a targeted e-commerce push across Germany, Austria, and Switzerland for Q3 2026. This campaign will highlight priority e-commerce lanes to SIN, HKG, and PVG with competitive yields and guaranteed space. GSA partners are invited to submit dedicated e-commerce account pipelines by May 31.",
    createdAt: "May 1, 2026",
  },
];

export const gsaCampaigns: Campaign[] = [
  {
    id: "gcmp-001",
    title: "DACH Market: AeroBridge Cargo Pharma Capacity Available",
    type: "capacity_highlight",
    status: "published",
    author: "BlueWing Cargo Solutions",
    authorRole: "gsa",
    channels: ["platform"],
    audience: "Local pharma accounts",
    body: "We are pleased to offer dedicated GDP-certified capacity on AeroBridge Cargo flights out of FRA and MUC. CEIV-pharma lanes to DXB and DOH are now open for booking. Contact our Frankfurt desk for slot confirmation and rate enquiries.",
    publishedAt: "Apr 22, 2026",
    createdAt: "Apr 20, 2026",
    reach: 74,
    engagement: 12,
  },
  {
    id: "gcmp-002",
    title: "New Frequency Alert: FRA–DXB Now 7x Weekly",
    type: "route_announcement",
    status: "published",
    author: "BlueWing Cargo Solutions",
    authorRole: "gsa",
    channels: ["platform"],
    audience: "Key accounts — DACH",
    body: "AeroBridge Cargo has increased its FRA–DXB service to 7 weekly freighter departures effective June 2026. As your appointed GSA for the DACH region, BlueWing Cargo Solutions can offer confirmed space on all departures. Reach out to lock in capacity before peak summer demand.",
    publishedAt: "Apr 29, 2026",
    createdAt: "Apr 28, 2026",
    reach: 91,
    engagement: 18,
  },
  {
    id: "gcmp-003",
    title: "Summer Push: SIN / HKG / PVG via AeroBridge",
    type: "promotion",
    status: "draft",
    author: "BlueWing Cargo Solutions",
    authorRole: "gsa",
    channels: ["platform"],
    audience: "E-commerce accounts",
    body: "Preparing a targeted outreach for our e-commerce accounts on the DACH–Asia Pacific corridor. AeroBridge Cargo is activating preferred e-commerce space on SIN, HKG, and PVG lanes for Q3. Draft pending airline capacity confirmation.",
    createdAt: "May 2, 2026",
  },
];
