import type {
  GsaProfile,
  KpiPoint,
  LinkedinSource,
  LinkedinImportRequest,
  LinkedinPostPreview,
  NewsCategory,
  NewsPost,
  Notification,
  Tender,
  TenderApplication,
} from "./types";

export const tenders: Tender[] = [
  {
    id: "tnd-eur-001",
    title: "Central Europe GSA representation",
    airline: "AeroBridge Cargo",
    regions: ["Germany", "Austria", "Switzerland"],
    lanes: "FRA, MUC, VIE to DXB, DOH, SIN",
    annualTonnage: 18400,
    productMix: "General cargo, pharma, express",
    deadline: "May 24, 2026",
    status: "open",
    expectedStart: "Q3 2026",
    requirements: ["GDP-certified pharma desk", "24/7 booking coverage", "Monthly route-level KPI reporting"],
  },
  {
    id: "tnd-iberia-002",
    title: "Iberia belly capacity sales launch",
    airline: "NorthStar Airways",
    regions: ["Spain", "Portugal"],
    lanes: "MAD, BCN, LIS to JFK, ORD, MEX",
    annualTonnage: 11200,
    productMix: "Perishables, e-commerce, mail",
    deadline: "Jun 3, 2026",
    status: "open",
    expectedStart: "Q4 2026",
    requirements: ["Perishables sales coverage", "IATA CASS experience", "Named key accounts pipeline"],
  },
  {
    id: "tnd-nordics-003",
    title: "Nordics freighter sales RFP",
    airline: "PolarLine Cargo",
    regions: ["Sweden", "Norway", "Denmark", "Finland"],
    lanes: "ARN, OSL, CPH, HEL to ICN, PVG, NRT",
    annualTonnage: 15600,
    productMix: "Tech, seafood, high value",
    deadline: "Jun 18, 2026",
    status: "open",
    expectedStart: "Q1 2027",
    requirements: ["Seafood handling track record", "ULD planning capability", "Local language sales teams"],
  },
];

export const gsaProfiles: GsaProfile[] = [
  {
    id: "gsa-bluewing",
    name: "BlueWing Cargo Solutions",
    headquarters: "Frankfurt, Germany",
    coverage: ["DACH", "Benelux", "CEE"],
    certifications: ["IATA", "GDP", "ISO 9001"],
    cargoFocus: "Pharma, automotive, express",
    networkScore: 92,
    financialScore: 88,
    complianceScore: 96,
    winRate: 41,
    summary: "Enterprise GSA with strong airline transition playbooks, dense DACH shipper relationships, and a pharma-focused operations desk.",
  },
  {
    id: "gsa-atlantic",
    name: "Atlantic AirCargo Partners",
    headquarters: "Madrid, Spain",
    coverage: ["Iberia", "Morocco", "France"],
    certifications: ["IATA", "CASS", "CEIV Fresh"],
    cargoFocus: "Perishables, mail, transatlantic belly cargo",
    networkScore: 86,
    financialScore: 83,
    complianceScore: 89,
    winRate: 36,
    summary: "Commercially aggressive Iberia specialist with strong perishables and passenger belly capacity sales programs.",
  },
  {
    id: "gsa-nordic",
    name: "NordicLift Aviation Services",
    headquarters: "Copenhagen, Denmark",
    coverage: ["Nordics", "Baltics"],
    certifications: ["IATA", "ISO 14001"],
    cargoFocus: "Seafood, technology, high-value cargo",
    networkScore: 89,
    financialScore: 81,
    complianceScore: 91,
    winRate: 33,
    summary: "Regional specialist with deep seafood exporter relationships and a proven launch history for Asian capacity.",
  },
];

export const applications: TenderApplication[] = [
  {
    id: "app-001",
    tenderId: "tnd-eur-001",
    gsaId: "gsa-bluewing",
    gsaName: "BlueWing Cargo Solutions",
    commercialScore: 91,
    networkScore: 94,
    complianceScore: 96,
    proposedCommission: "5.8% base + 1.2% accelerator",
    status: "shortlisted",
    submittedAt: "Apr 21, 2026",
  },
  {
    id: "app-002",
    tenderId: "tnd-eur-001",
    gsaId: "gsa-atlantic",
    gsaName: "Atlantic AirCargo Partners",
    commercialScore: 84,
    networkScore: 78,
    complianceScore: 88,
    proposedCommission: "5.1% fixed",
    status: "pending",
    submittedAt: "Apr 22, 2026",
  },
  {
    id: "app-003",
    tenderId: "tnd-nordics-003",
    gsaId: "gsa-nordic",
    gsaName: "NordicLift Aviation Services",
    commercialScore: 87,
    networkScore: 91,
    complianceScore: 90,
    proposedCommission: "6.0% base + launch bonus",
    status: "accepted",
    submittedAt: "Apr 19, 2026",
  },
];

export const kpiSeries: KpiPoint[] = [
  { month: "Nov", revenue: 820000, loadfactor: 61, yield: 2.08 },
  { month: "Dec", revenue: 910000, loadfactor: 65, yield: 2.14 },
  { month: "Jan", revenue: 970000, loadfactor: 68, yield: 2.21 },
  { month: "Feb", revenue: 1020000, loadfactor: 71, yield: 2.24 },
  { month: "Mar", revenue: 1180000, loadfactor: 74, yield: 2.31 },
  { month: "Apr", revenue: 1260000, loadfactor: 77, yield: 2.38 },
];

export const newsCategories: NewsCategory[] = [
  "GSA opportunity",
  "airline expansion",
  "new route",
  "cargo capacity",
  "tender/RFP",
  "partnership",
];

export const newsPosts: NewsPost[] = [
  {
    id: "news-001",
    title: "AeroBridge Cargo evaluates DACH sales representation for new Middle East lanes",
    source: "LinkedIn: AeroBridge Cargo",
    category: "GSA opportunity",
    market: "DACH",
    publishedAt: "Apr 27, 2026",
    summary: "Carrier signaled a commercial build-out tied to Frankfurt and Munich departures, with pharma and express cargo named as focus verticals.",
    confidence: 92,
  },
  {
    id: "news-002",
    title: "NorthStar Airways adds Madrid and Lisbon widebody rotations",
    source: "LinkedIn: NorthStar Airways",
    category: "airline expansion",
    market: "Iberia",
    publishedAt: "Apr 26, 2026",
    summary: "New long-haul passenger capacity creates belly cargo availability across JFK, ORD, and Mexico City lanes from Q4.",
    confidence: 87,
  },
  {
    id: "news-003",
    title: "PolarLine Cargo opens seafood-focused RFP for Nordic export markets",
    source: "LinkedIn: PolarLine Cargo",
    category: "tender/RFP",
    market: "Nordics",
    publishedAt: "Apr 25, 2026",
    summary: "The post references a formal partner selection process for freighter capacity serving Asia-bound seafood and technology shippers.",
    confidence: 94,
  },
  {
    id: "news-004",
    title: "SkyHarbor signs handling partnership at Vienna for temperature-controlled cargo",
    source: "LinkedIn: SkyHarbor Logistics",
    category: "partnership",
    market: "Central Europe",
    publishedAt: "Apr 24, 2026",
    summary: "The agreement adds cool-chain handling capacity and may support new airline commercial programs in Austria.",
    confidence: 78,
  },
];

export const linkedinSources: LinkedinSource[] = [
  {
    id: "src-001",
    name: "Oman Air Cargo",
    url: "https://www.linkedin.com/showcase/omanair-cargo/posts/?feedView=all",
    category: "cargo capacity",
    status: "active",
    lastImport: "Apr 27, 2026 08:10",
  },
  {
    id: "src-002",
    name: "Etihad Cargo",
    url: "https://www.linkedin.com/showcase/etihad-cargo/posts/?feedView=all",
    category: "airline expansion",
    status: "active",
    lastImport: "Apr 26, 2026 16:45",
  },
  {
    id: "src-003",
    name: "PolarLine Cargo",
    url: "https://www.linkedin.com/company/polarline-cargo/posts/?feedView=all",
    category: "tender/RFP",
    status: "paused",
    lastImport: "Apr 25, 2026 11:20",
  },
];

export const linkedinImportDefaults: LinkedinImportRequest = {
  includeQuotePosts: false,
  includeReposts: false,
  maxComments: 0,
  maxPosts: 50,
  maxReactions: 0,
  postNestedComments: false,
  postNestedReactions: false,
  postedLimit: "any",
  scrapeComments: false,
  scrapeReactions: false,
  targetUrls: linkedinSources.filter((source) => source.status === "active").map((source) => source.url),
};

export const linkedinPostPreview: LinkedinPostPreview = {
  id: "7329207003942125568",
  linkedinUrl:
    "https://www.linkedin.com/posts/williamhgates_how-better-data-helped-us-cut-child-mortality-activity-7329207003942125568-_gfJ",
  authorName: "Bill Gates",
  authorUrl: "https://www.linkedin.com/in/williamhgates",
  content:
    "The leading causes of childhood death reveal a stark truth: Many could be prevented, and children in poor countries die from them far more often than those in wealthy ones.",
  postedAt: "2025-05-16T18:11:59.821Z",
  media: [
    {
      type: "document",
      title: "How better data helped us cut child mortality in half",
      url: "https://media.licdn.com/dms/document/media/v2/D561FAQGPMwZUeWRF4w/feedshare-document-pdf-analyzed",
    },
    {
      type: "image",
      title: "Document cover page",
      url: "https://media.licdn.com/dms/image/v2/D561FAQGPMwZUeWRF4w/feedshare-document-cover-images_1920",
      width: 1921,
      height: 1243,
    },
  ],
};

export const notifications: Notification[] = [
  {
    id: "ntf-001",
    title: "Shortlist update",
    body: "BlueWing Cargo Solutions moved to shortlist for Central Europe representation.",
    time: "18 min ago",
    status: "unread",
  },
  {
    id: "ntf-002",
    title: "Tender deadline reminder",
    body: "Nordics freighter sales RFP closes in 51 days.",
    time: "2 hr ago",
    status: "unread",
  },
  {
    id: "ntf-003",
    title: "New opportunity match",
    body: "NorthStar Iberia launch matches your perishables coverage profile.",
    time: "Yesterday",
    status: "read",
  },
];
