import { realGsaApplications, realGsaProfiles } from "./real-gsa-data";
import type {
  Campaign,
  GsaProfile,
  KpiPoint,
  LinkedinSource,
  LinkedinImportRequest,
  LinkedinPostPreview,
  NewsCategory,
  NewsPost,
  Notification,
  Tender,
  TenderApplication,
} from "./types";

export const tenders: Tender[] = [
  {
    id: "tnd-eur-001",
    title: "DACH & Benelux freighter GSA representation",
    airline: "Saudia Cargo",
    regions: ["Germany", "Austria", "Switzerland", "Netherlands", "Belgium"],
    lanes: "FRA, MUC, VIE, AMS to JED, RUH",
    annualTonnage: 22400,
    productMix: "General cargo, pharma, express, high-value",
    deadline: "May 24, 2026",
    status: "open",
    expectedStart: "Q3 2026",
    requirements: ["GDP-certified pharma desk", "24/7 booking coverage", "Monthly route-level KPI reporting"],
  },
  {
    id: "tnd-iberia-002",
    title: "Iberia & France belly capacity launch",
    airline: "Saudia Cargo",
    regions: ["Spain", "Portugal", "France"],
    lanes: "MAD, BCN, LIS, CDG to JED, RUH",
    annualTonnage: 14800,
    productMix: "Perishables, e-commerce, general cargo",
    deadline: "Jun 3, 2026",
    status: "open",
    expectedStart: "Q4 2026",
    requirements: ["Perishables sales coverage", "IATA CASS experience", "Named key accounts pipeline"],
  },
  {
    id: "tnd-nordics-003",
    title: "Nordics & UK freighter sales RFP",
    airline: "Saudia Cargo",
    regions: ["United Kingdom", "Sweden", "Norway", "Denmark", "Finland"],
    lanes: "LHR, ARN, OSL, CPH, HEL to JED, RUH",
    annualTonnage: 18200,
    productMix: "Tech, pharma, high-value, general cargo",
    deadline: "Jun 18, 2026",
    status: "open",
    expectedStart: "Q1 2027",
    requirements: ["Pharma/high-value handling capability", "ULD planning capability", "Local language sales teams"],
  },
];

export const gsaProfiles: GsaProfile[] = realGsaProfiles;

export const applications: TenderApplication[] = realGsaApplications;

export const kpiSeries: KpiPoint[] = [
  { month: "Apr", date: "2025-04", revenue: 695000, loadfactor: 56, yield: 1.93 },
  { month: "May", date: "2025-05", revenue: 710000, loadfactor: 57, yield: 1.95 },
  { month: "Jun", date: "2025-06", revenue: 730000, loadfactor: 58, yield: 1.97 },
  { month: "Jul", date: "2025-07", revenue: 755000, loadfactor: 59, yield: 1.99 },
  { month: "Aug", date: "2025-08", revenue: 780000, loadfactor: 60, yield: 2.02 },
  { month: "Sep", date: "2025-09", revenue: 795000, loadfactor: 61, yield: 2.04 },
  { month: "Oct", date: "2025-10", revenue: 805000, loadfactor: 62, yield: 2.06 },
  { month: "Nov", date: "2025-11", revenue: 820000, loadfactor: 61, yield: 2.08 },
  { month: "Dec", date: "2025-12", revenue: 910000, loadfactor: 65, yield: 2.14 },
  { month: "Jan", date: "2026-01", revenue: 970000, loadfactor: 68, yield: 2.21 },
  { month: "Feb", date: "2026-02", revenue: 1020000, loadfactor: 71, yield: 2.24 },
  { month: "Mar", date: "2026-03", revenue: 1180000, loadfactor: 74, yield: 2.31 },
  { month: "Apr", date: "2026-04", revenue: 1260000, loadfactor: 77, yield: 2.38 },
];

export const newsCategories: NewsCategory[] = [
  "GSA opportunity",
  "airline expansion",
  "new route",
  "cargo capacity",
  "tender/RFP",
  "partnership",
];

export const newsPosts: NewsPost[] = [
  {
    id: "news-001",
    title: "Saudia Cargo expands freighter frequency to Europe for Summer 2026",
    source: "LinkedIn: Saudia Cargo",
    category: "airline expansion",
    market: "Europe",
    publishedAt: "Apr 27, 2026",
    summary: "Carrier signals additional B747-8F rotations on JED–FRA and JED–LHR corridors, with pharma and express cargo listed as priority verticals for the new capacity.",
    confidence: 94,
  },
  {
    id: "news-002",
    title: "Saudia Cargo opens DACH & Benelux GSA representation RFP",
    source: "LinkedIn: Saudia Cargo",
    category: "GSA opportunity",
    market: "DACH",
    publishedAt: "Apr 26, 2026",
    summary: "Formal tender published for a GSA partner to manage cargo sales across Germany, Austria, Switzerland, Netherlands and Belgium — submission deadline May 24, 2026.",
    confidence: 97,
  },
  {
    id: "news-003",
    title: "Saudi non-oil exports drive record cargo volumes at JED in Q1 2026",
    source: "LinkedIn: Saudi Cargo Industry",
    category: "cargo capacity",
    market: "Middle East",
    publishedAt: "Apr 25, 2026",
    summary: "King Abdulaziz International Airport reports record year-on-year tonnage growth, driven by pharmaceutical exports and Vision 2030 diversification momentum.",
    confidence: 89,
  },
  {
    id: "news-004",
    title: `${realGsaProfiles[0].name} shortlisted for Saudia Cargo DACH representation`,
    source: `LinkedIn: ${realGsaProfiles[0].name}`,
    category: "GSA opportunity",
    market: "DACH",
    publishedAt: "Apr 24, 2026",
    summary: `${realGsaProfiles[0].name} confirmed as one of three shortlisted GSA candidates for Saudia Cargo's DACH representation program, citing pharma desk capability and DACH shipper network.`,
    confidence: 82,
  },
];

export const linkedinSources: LinkedinSource[] = [
  {
    id: "src-001",
    name: "Saudia Cargo",
    url: "https://www.linkedin.com/company/saudia-cargo/posts/?feedView=all",
    category: "cargo capacity",
    status: "active",
    lastImport: "Apr 27, 2026 08:10",
  },
  {
    id: "src-002",
    name: "Etihad Cargo",
    url: "https://www.linkedin.com/showcase/etihad-cargo/posts/?feedView=all",
    category: "airline expansion",
    status: "active",
    lastImport: "Apr 26, 2026 16:45",
  },
  {
    id: "src-003",
    name: "Qatar Airways Cargo",
    url: "https://www.linkedin.com/showcase/qatar-airways-cargo/posts/?feedView=all",
    category: "GSA opportunity",
    status: "active",
    lastImport: "Apr 25, 2026 11:20",
  },
];

export const linkedinImportDefaults: LinkedinImportRequest = {
  includeQuotePosts: false,
  includeReposts: false,
  maxComments: 0,
  maxPosts: 50,
  maxReactions: 0,
  postNestedComments: false,
  postNestedReactions: false,
  postedLimit: "any",
  scrapeComments: false,
  scrapeReactions: false,
  targetUrls: linkedinSources.filter((source) => source.status === "active").map((source) => source.url),
};

export const linkedinPostPreview: LinkedinPostPreview = {
  id: "7329207003942125568",
  linkedinUrl:
    "https://www.linkedin.com/posts/williamhgates_how-better-data-helped-us-cut-child-mortality-activity-7329207003942125568-_gfJ",
  authorName: "Bill Gates",
  authorUrl: "https://www.linkedin.com/in/williamhgates",
  content:
    "The leading causes of childhood death reveal a stark truth: Many could be prevented, and children in poor countries die from them far more often than those in wealthy ones.",
  postedAt: "2025-05-16T18:11:59.821Z",
  media: [
    {
      type: "document",
      title: "How better data helped us cut child mortality in half",
      url: "https://media.licdn.com/dms/document/media/v2/D561FAQGPMwZUeWRF4w/feedshare-document-pdf-analyzed",
    },
    {
      type: "image",
      title: "Document cover page",
      url: "https://media.licdn.com/dms/image/v2/D561FAQGPMwZUeWRF4w/feedshare-document-cover-images_1920",
      width: 1921,
      height: 1243,
    },
  ],
};

export const notifications: Notification[] = [
  {
    id: "ntf-001",
    title: "Shortlist update",
    body: `${realGsaProfiles[0].name} moved to shortlist for Central Europe representation.`,
    time: "18 min ago",
    status: "unread",
  },
  {
    id: "ntf-002",
    title: "Tender deadline reminder",
    body: "Nordics freighter sales RFP closes in 51 days.",
    time: "2 hr ago",
    status: "unread",
  },
  {
    id: "ntf-003",
    title: "New opportunity match",
    body: "NorthStar Iberia launch matches your perishables coverage profile.",
    time: "Yesterday",
    status: "read",
  },
];

export const airlineCampaigns: Campaign[] = [
  {
    id: "cmp-001",
    title: "JED–FRA Frequency Increase — Summer 2026",
    type: "route_announcement",
    status: "published",
    author: "Saudia Cargo",
    authorRole: "airline",
    channels: ["platform"],
    audience: "All GSA partners",
    body: "We are pleased to announce an increase in freighter frequency on the Jeddah–Frankfurt corridor starting 1 June 2026. Weekly B747-8F departures will rise from 5 to 7, adding approximately 160 tonnes of available capacity per week. Priority product allocation applies to pharma and express categories. Please update your sales pipeline accordingly and reach out to your account manager for AWB block allocation.",
    bannerImageUrl: "https://images.unsplash.com/photo-1521727857535-28d2047314ac?auto=format&fit=crop&w=1200&q=80",
    publishedAt: "Apr 28, 2026",
    createdAt: "Apr 25, 2026",
    reach: 312,
    engagement: 48,
  },
  {
    id: "cmp-002",
    title: "Q2 Pharma Capacity: Priority Lane Activation",
    type: "capacity_highlight",
    status: "published",
    author: "Saudia Cargo",
    authorRole: "airline",
    channels: ["platform"],
    audience: "All GSA partners",
    body: "Saudia Cargo is activating dedicated IATA CEIV-certified pharma capacity on JED–FRA, JED–ZRH, and JED–AMS lanes for Q2 2026. All lanes feature real-time temperature monitoring and Saudi SFDA-compliant handling documentation. Minimum booking lead time is 48 hours. GDP documentation must accompany all shipments. Capacity is allocated on a first-come basis — contact your regional desk to secure slots.",
    airlineLogoUrl: "/globe.svg",
    publishedAt: "Apr 15, 2026",
    createdAt: "Apr 12, 2026",
    reach: 284,
    engagement: 61,
  },
  {
    id: "cmp-003",
    title: "Summer 2026 Network Expansion — Preview",
    type: "news_update",
    status: "scheduled",
    author: "Saudia Cargo",
    authorRole: "airline",
    channels: ["platform"],
    audience: "All GSA partners",
    body: "Saudia Cargo will announce three additional freighter destinations for the Summer 2026 schedule: Lagos (LOS), Nairobi (NBO), and São Paulo (GRU). Detailed capacity, frequency, and product mix information will follow. GSA partners with existing coverage in these markets are encouraged to express interest ahead of formal tender publication.",
    scheduledFor: "May 10, 2026",
    createdAt: "Apr 30, 2026",
  },
  {
    id: "cmp-004",
    title: "DACH E-Commerce Launch — Partner Activation",
    type: "promotion",
    status: "draft",
    author: "Saudia Cargo",
    authorRole: "airline",
    channels: ["platform"],
    audience: "DACH GSA partners",
    body: "We are preparing a targeted e-commerce push across Germany, Austria, and Switzerland for Q3 2026. This campaign will highlight priority e-commerce lanes from JED to SIN, HKG, and CGO with competitive yields and guaranteed space. GSA partners are invited to submit dedicated e-commerce account pipelines by May 31.",
    createdAt: "May 1, 2026",
  },
];

export const gsaCampaigns: Campaign[] = [
  {
    id: "gcmp-001",
    title: "DACH Market: Saudia Cargo Pharma Capacity Now Available",
    type: "capacity_highlight",
    status: "published",
    author: realGsaProfiles[0].name,
    authorRole: "gsa",
    channels: ["platform"],
    audience: "Local pharma accounts",
    body: "We are pleased to offer dedicated GDP-certified capacity on Saudia Cargo B747-8F freighters departing FRA and MUC. CEIV-pharma lanes to JED with connections to Riyadh, Doha, and Dubai are now open for booking. Contact our Frankfurt desk for slot confirmation and rate enquiries.",
    publishedAt: "Apr 22, 2026",
    createdAt: "Apr 20, 2026",
    reach: 74,
    engagement: 12,
  },
  {
    id: "gcmp-002",
    title: "Frequency Alert: JED–FRA Now 7x Weekly",
    type: "route_announcement",
    status: "published",
    author: realGsaProfiles[0].name,
    authorRole: "gsa",
    channels: ["platform"],
    audience: "Key accounts — DACH",
    body: `Saudia Cargo has increased its JED-FRA freighter service to 7 weekly departures effective June 2026. As appointed GSA for the DACH region, ${realGsaProfiles[0].name} can offer confirmed space on all departures including Middle East connections beyond Jeddah. Reach out to lock in capacity before peak summer demand.`,
    publishedAt: "Apr 29, 2026",
    createdAt: "Apr 28, 2026",
    reach: 91,
    engagement: 18,
  },
  {
    id: "gcmp-003",
    title: "Asia Push: SIN / HKG / CGO via Saudia Cargo JED hub",
    type: "promotion",
    status: "draft",
    author: realGsaProfiles[0].name,
    authorRole: "gsa",
    channels: ["platform"],
    audience: "E-commerce accounts",
    body: "Preparing a targeted outreach for DACH e-commerce accounts on the Asia Pacific corridor via Jeddah hub. Saudia Cargo is activating preferred e-commerce space on SIN, HKG, and CGO lanes for Q3. Draft pending airline capacity confirmation.",
    createdAt: "May 2, 2026",
  },
];
