import type { GsaProfile, TenderApplication } from "./types";

export type RealGsaPartner = {
  id: string;
  name: string;
  contactName: string;
  email: string;
  country: "Germany" | "France" | "United Kingdom";
  headquarters: string;
  coverage: string[];
  markets: string[];
  certifications: string[];
  cargoFocus: string;
  color: string;
  networkScore: number;
  financialScore: number;
  complianceScore: number;
  winRate: number;
  summary: string;
};

export const realGsaPartners: RealGsaPartner[] = [
  {
    id: "gsa-aeb",
    name: "AEB",
    contactName: "Ian Crauwels",
    email: "ian.crauwels@aeb.com",
    country: "Germany",
    headquarters: "Stuttgart, Germany",
    coverage: ["Germany", "DACH", "Benelux"],
    markets: ["DACH", "Benelux"],
    certifications: ["IATA", "CASS", "GDP"],
    cargoFocus: "General cargo, pharma, industrial freight",
    color: "#0066CC",
    networkScore: 91,
    financialScore: 86,
    complianceScore: 94,
    winRate: 39,
    summary: "Germany-based cargo sales partner with strong DACH forwarder coverage and reliable pharma-capable account handling.",
  },
  {
    id: "gsa-aerotrans",
    name: "Aerotrans Luftfahrtagentur GmbH",
    contactName: "Mike Jaensch",
    email: "jaensch@aerotrans.de",
    country: "Germany",
    headquarters: "Dusseldorf, Germany",
    coverage: ["Germany", "Austria", "Switzerland"],
    markets: ["DACH"],
    certifications: ["IATA", "CASS"],
    cargoFocus: "Aerospace, general cargo, time-critical",
    color: "#F97316",
    networkScore: 88,
    financialScore: 84,
    complianceScore: 90,
    winRate: 35,
    summary: "Established aviation sales agency for DACH cargo programs, with practical airline representation and route launch experience.",
  },
  {
    id: "gsa-critical-logistics",
    name: "Critical Logistics GmbH",
    contactName: "Yasar Maras",
    email: "yasar@criticallogistics.de",
    country: "Germany",
    headquarters: "Frankfurt Am Main, Germany",
    coverage: ["Germany", "Central Europe"],
    markets: ["DACH", "CEE"],
    certifications: ["IATA", "GDP", "ISO 9001"],
    cargoFocus: "Time-critical, automotive, high-value",
    color: "#22C55E",
    networkScore: 86,
    financialScore: 82,
    complianceScore: 92,
    winRate: 34,
    summary: "Time-critical specialist with strong shipper access for urgent automotive, machinery and premium cargo movements.",
  },
  {
    id: "gsa-forto",
    name: "Forto Logistics",
    contactName: "Christopher Braun",
    email: "christopher.braun@forto.com",
    country: "Germany",
    headquarters: "Berlin, Germany",
    coverage: ["Germany", "Europe", "Asia trade lanes"],
    markets: ["DACH", "Asia"],
    certifications: ["IATA", "CASS", "ISO 9001"],
    cargoFocus: "Digital freight, e-commerce, general cargo",
    color: "#8B5CF6",
    networkScore: 89,
    financialScore: 88,
    complianceScore: 87,
    winRate: 36,
    summary: "Digital freight forwarder with scalable customer coverage and strong data-led sales potential for e-commerce lanes.",
  },
  {
    id: "gsa-mycargogate",
    name: "mycargogate GmbH",
    contactName: "Tanja Muller",
    email: "tmueller@mycargogate.com",
    country: "Germany",
    headquarters: "Rheinfelden, Germany",
    coverage: ["Germany", "DACH"],
    markets: ["DACH"],
    certifications: ["IATA", "CASS"],
    cargoFocus: "Digital cargo booking, SME forwarders, consolidations",
    color: "#0EA5E9",
    networkScore: 84,
    financialScore: 81,
    complianceScore: 86,
    winRate: 30,
    summary: "Digital cargo sales channel with useful SME forwarder reach and fast conversion for spot-capacity campaigns.",
  },
  {
    id: "gsa-on-air-cargo",
    name: "On Air Cargo GmbH",
    contactName: "Onur Uykiz",
    email: "onur@onair-cargo.com",
    country: "Germany",
    headquarters: "Dusseldorf, Germany",
    coverage: ["Germany", "Austria", "Turkey"],
    markets: ["DACH", "Turkey"],
    certifications: ["IATA", "CASS"],
    cargoFocus: "General cargo, express, cross-border trucking",
    color: "#14B8A6",
    networkScore: 83,
    financialScore: 80,
    complianceScore: 85,
    winRate: 29,
    summary: "Commercially flexible cargo sales partner with strong regional relationships and useful Turkey-Europe lane knowledge.",
  },
  {
    id: "gsa-priority-freight",
    name: "Priority Freight Europe GmbH",
    contactName: "Marco Sauer",
    email: "marco.sauer@priorityfreight.com",
    country: "Germany",
    headquarters: "Frankfurt Am Main, Germany",
    coverage: ["Germany", "Europe"],
    markets: ["DACH", "Europe"],
    certifications: ["IATA", "GDP", "ISO 9001"],
    cargoFocus: "Automotive, AOG, emergency logistics",
    color: "#EF4444",
    networkScore: 87,
    financialScore: 83,
    complianceScore: 91,
    winRate: 33,
    summary: "Emergency logistics specialist with high-value urgent freight access and mature operational control for premium cargo.",
  },
  {
    id: "gsa-quivo",
    name: "Quivo (Ancla Logistik GmbH)",
    contactName: "Torben Lenhart",
    email: "torben.lenhart@quivo.co",
    country: "Germany",
    headquarters: "Wetzlar, Germany",
    coverage: ["Germany", "Austria", "CEE"],
    markets: ["DACH", "CEE"],
    certifications: ["IATA", "ISO 9001"],
    cargoFocus: "E-commerce, fulfillment, parcel cargo",
    color: "#A855F7",
    networkScore: 85,
    financialScore: 82,
    complianceScore: 84,
    winRate: 31,
    summary: "E-commerce and fulfillment-oriented logistics partner with good fit for parcel-heavy belly and freighter capacity.",
  },
  {
    id: "gsa-share-logistics",
    name: "Share Logistics GmbH",
    contactName: "Lucas Goesling",
    email: "lgs@sharelogistics.com",
    country: "Germany",
    headquarters: "Hamburg, Germany",
    coverage: ["Germany", "Benelux", "Global forwarding network"],
    markets: ["DACH", "Benelux"],
    certifications: ["IATA", "CASS", "ISO 9001"],
    cargoFocus: "Consolidations, general cargo, project cargo",
    color: "#64748B",
    networkScore: 86,
    financialScore: 84,
    complianceScore: 88,
    winRate: 32,
    summary: "Network-driven forwarding partner with solid consolidation flows and broad airline-compatible account coverage.",
  },
  {
    id: "gsa-teconja",
    name: "Speditionsgesellschaft Teconja mbH",
    contactName: "Marc Schmitz",
    email: "mschmitz@teconja.de",
    country: "Germany",
    headquarters: "Weiterstadt, Germany",
    coverage: ["Germany", "Western Europe"],
    markets: ["DACH", "Western Europe"],
    certifications: ["IATA", "CASS"],
    cargoFocus: "Industrial cargo, machinery, general freight",
    color: "#D97706",
    networkScore: 80,
    financialScore: 79,
    complianceScore: 84,
    winRate: 27,
    summary: "Industrial freight specialist with practical regional account coverage and stable mid-market customer relationships.",
  },
  {
    id: "gsa-talogis",
    name: "Talogis Air & Sea GmbH",
    contactName: "Christian Opszalski",
    email: "christian.opszalski@talogis.de",
    country: "Germany",
    headquarters: "Dusseldorf, Germany",
    coverage: ["Germany", "North Europe", "Asia trade lanes"],
    markets: ["DACH", "Asia"],
    certifications: ["IATA", "CASS"],
    cargoFocus: "Air & sea forwarding, consolidations, general cargo",
    color: "#059669",
    networkScore: 82,
    financialScore: 80,
    complianceScore: 85,
    winRate: 28,
    summary: "Air and sea logistics partner with useful consolidation traffic and balanced general cargo sales potential.",
  },
  {
    id: "gsa-tci",
    name: "TCI International Logistics GmbH",
    contactName: "Serkan Ertal",
    email: "s.ertal@mytcigroup.com",
    country: "Germany",
    headquarters: "Kelsterbach, Germany",
    coverage: ["Germany", "Europe", "Middle East"],
    markets: ["DACH", "Middle East"],
    certifications: ["IATA", "CASS", "ISO 9001"],
    cargoFocus: "General cargo, textile, e-commerce",
    color: "#2563EB",
    networkScore: 83,
    financialScore: 81,
    complianceScore: 86,
    winRate: 29,
    summary: "International logistics partner with useful Middle East trade-lane relevance and broad German customer coverage.",
  },
  {
    id: "gsa-cargo-airlines-services",
    name: "Cargo Airlines Services SAS",
    contactName: "Cedric Lepretre",
    email: "cedric@cargoairlines.aero",
    country: "France",
    headquarters: "Paris, France",
    coverage: ["France", "Benelux", "Southern Europe"],
    markets: ["France", "Benelux"],
    certifications: ["IATA", "CASS", "GDP"],
    cargoFocus: "Airline representation, pharma, general cargo",
    color: "#DC2626",
    networkScore: 90,
    financialScore: 85,
    complianceScore: 93,
    winRate: 38,
    summary: "France-based airline cargo representation specialist with strong forwarder coverage and mature sales processes.",
  },
  {
    id: "gsa-eas-france",
    name: "EAS France",
    contactName: "Marco Muggianu",
    email: "marco.muggianu@eas-intl.com",
    country: "France",
    headquarters: "Paris, France",
    coverage: ["France", "Western Europe"],
    markets: ["France"],
    certifications: ["IATA", "CASS"],
    cargoFocus: "General cargo, express, charter support",
    color: "#EA580C",
    networkScore: 84,
    financialScore: 80,
    complianceScore: 86,
    winRate: 30,
    summary: "French cargo sales partner with practical airline support capability and broad local forwarder relationships.",
  },
  {
    id: "gsa-logfret",
    name: "Logfret",
    contactName: "Stephane Caillot",
    email: "scaillot@multimodal.fr",
    country: "France",
    headquarters: "Aulnay-sous-Bois, France",
    coverage: ["France", "Europe", "Overseas markets"],
    markets: ["France", "Overseas"],
    certifications: ["IATA", "CASS", "ISO 9001"],
    cargoFocus: "Consolidations, overseas cargo, general freight",
    color: "#9333EA",
    networkScore: 86,
    financialScore: 83,
    complianceScore: 87,
    winRate: 32,
    summary: "Established logistics network with strong overseas flow knowledge and good fit for structured capacity programs.",
  },
  {
    id: "gsa-neutral-freight",
    name: "Neutral Freight Services SAS",
    contactName: "Helene Dimopoulou",
    email: "helene@neutralfreight.com",
    country: "France",
    headquarters: "Paris, France",
    coverage: ["France", "Europe", "North Africa"],
    markets: ["France", "North Africa"],
    certifications: ["IATA", "CASS"],
    cargoFocus: "Neutral wholesale, consolidations, general cargo",
    color: "#0891B2",
    networkScore: 85,
    financialScore: 82,
    complianceScore: 86,
    winRate: 31,
    summary: "Neutral freight partner with wholesale consolidation reach and practical access to forwarder-heavy account pools.",
  },
  {
    id: "gsa-sky-art",
    name: "Sky Art Services SAS",
    contactName: "Damien Rizzo",
    email: "damien.rizzo@skyart-services.com",
    country: "France",
    headquarters: "Paris, France",
    coverage: ["France", "Southern Europe"],
    markets: ["France", "Southern Europe"],
    certifications: ["IATA", "CASS"],
    cargoFocus: "Special cargo, project cargo, high-value",
    color: "#4F46E5",
    networkScore: 82,
    financialScore: 79,
    complianceScore: 85,
    winRate: 28,
    summary: "Special cargo-oriented partner with useful niche account access and flexible operational support.",
  },
  {
    id: "gsa-sparta-cargo",
    name: "Sparta Cargo France",
    contactName: "Frederic Durepaire",
    email: "fred@spartacargo.fr",
    country: "France",
    headquarters: "Paris, France",
    coverage: ["France", "Europe"],
    markets: ["France", "Europe"],
    certifications: ["IATA", "CASS", "GDP"],
    cargoFocus: "Pharma, general cargo, perishables",
    color: "#16A34A",
    networkScore: 87,
    financialScore: 81,
    complianceScore: 91,
    winRate: 34,
    summary: "France cargo partner with strong pharma and general cargo sales fit for airline capacity campaigns.",
  },
  {
    id: "gsa-air-business",
    name: "Air Business",
    contactName: "Darrell Sweeney",
    email: "darrell.sweeney@airbusiness.com",
    country: "United Kingdom",
    headquarters: "Hatfield, United Kingdom",
    coverage: ["United Kingdom", "Ireland", "Europe"],
    markets: ["UK", "Ireland"],
    certifications: ["IATA", "CASS", "ISO 9001"],
    cargoFocus: "Mail, e-commerce, express cargo",
    color: "#0F766E",
    networkScore: 88,
    financialScore: 86,
    complianceScore: 89,
    winRate: 35,
    summary: "UK logistics and air cargo partner with strong mail, e-commerce and express account relevance.",
  },
  {
    id: "gsa-air-menzies",
    name: "Air Menzies International",
    contactName: "Samantha Leaper",
    email: "samantha.leaper@airmenzies.com",
    country: "United Kingdom",
    headquarters: "Crawley, United Kingdom",
    coverage: ["United Kingdom", "Ireland", "Global network"],
    markets: ["UK", "Ireland", "Global"],
    certifications: ["IATA", "CASS", "GDP"],
    cargoFocus: "Wholesale air cargo, pharma, express",
    color: "#7C3AED",
    networkScore: 92,
    financialScore: 87,
    complianceScore: 94,
    winRate: 40,
    summary: "Major UK wholesale air cargo partner with global network access and strong airline-compatible sales operations.",
  },
];

export const realGsaProfiles: GsaProfile[] = realGsaPartners.map((partner) => ({
  id: partner.id,
  name: partner.name,
  headquarters: partner.headquarters,
  coverage: partner.coverage,
  certifications: partner.certifications,
  cargoFocus: partner.cargoFocus,
  networkScore: partner.networkScore,
  financialScore: partner.financialScore,
  complianceScore: partner.complianceScore,
  winRate: partner.winRate,
  summary: partner.summary,
}));

export const realGsaApplications: TenderApplication[] = realGsaPartners.map((partner, index) => {
  const tenders = ["tnd-eur-001", "tnd-iberia-002", "tnd-nordics-003"];
  const statusCycle: TenderApplication["status"][] = ["shortlisted", "pending", "accepted", "pending", "rejected"];
  const aiRating = Math.min(4.9, Math.max(3.2, 3.4 + (partner.networkScore + partner.complianceScore - 160) / 40));

  return {
    id: `app-${String(index + 1).padStart(3, "0")}`,
    tenderId: tenders[index % tenders.length],
    gsaId: partner.id,
    gsaName: partner.name,
    aiRating: Math.round(aiRating * 10) / 10,
    commercialScore: Math.round((partner.financialScore + partner.winRate) / 2 + 20),
    networkScore: partner.networkScore,
    complianceScore: partner.complianceScore,
    proposedCommission: `${(4.8 + (index % 7) * 0.2).toFixed(1)}% base + KPI accelerator`,
    status: statusCycle[index % statusCycle.length],
    submittedAt: `May ${String(1 + index).padStart(2, "0")}, 2026`,
  };
});

export const realGsaFlightPartners = realGsaPartners.map(({ name, color, markets }) => ({
  name,
  color,
  markets,
}));

export function getRealGsaById(id: string) {
  return realGsaPartners.find((partner) => partner.id === id) ?? null;
}
