export type EcargowareMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";

export type EcargowareOperation = {
  id: string;
  group: string;
  label: string;
  method: EcargowareMethod;
  path: string;
  description: string;
  bodyExample?: unknown;
  queryExample?: Record<string, string>;
  pathParams?: string[];
  destructive?: boolean;
};

export const ECARGOWARE_BASE_URL = "https://qa.fr8manage.app";

export const ECARGOWARE_OPERATIONS: EcargowareOperation[] = [
  {
    id: "customers-search",
    group: "Customers",
    label: "Search customers",
    method: "POST",
    path: "/cargo-api/v1/customers/search",
    description: "Search customers by company, type, city, country, IATA number, CASS status, or VAT.",
    bodyExample: { companyName: "DHL", companyType: "Agent", country: "DE", transactionType: "CASS" },
  },
  {
    id: "customers-create",
    group: "Customers",
    label: "Create customer",
    method: "POST",
    path: "/cargo-api/v1/customers/create",
    description: "Create a company/customer record.",
    bodyExample: {
      companyCode: "DHL001",
      companyName: "DHL Germany GmbH",
      companyTypes: ["Agent"],
      iataNo: "12345678901",
      country: "DE",
      city: "Frankfurt",
      email: "cargo@example.com",
      currency: "EUR",
      transactionType: "CASS",
    },
  },
  {
    id: "customers-update",
    group: "Customers",
    label: "Update customer",
    method: "PATCH",
    path: "/cargo-api/v1/customers/update",
    description: "Update a customer. companyCode and companyName must match system records.",
    bodyExample: { companyCode: "DHL001", companyName: "DHL Germany GmbH", city: "Frankfurt", email: "ops@example.com" },
  },
  {
    id: "bookings-create",
    group: "Bookings",
    label: "Create booking",
    method: "POST",
    path: "/cargo-api/v1/bookings/create",
    description: "Create an operational booking.",
    bodyExample: {
      origin: "FRA",
      destination: "JED",
      grossweight: 100.5,
      chargeweight: 100.5,
      pieces: 5,
      flight: "SV1234",
      flightDate: "2026-06-01",
      commodity: "GEN",
      shc: "PER",
      agentName: "DHL Germany GmbH",
      iataNo: "12345678901",
      productType: "GENERAL",
      stackable: "Y",
    },
  },
  {
    id: "bookings-cancel",
    group: "Bookings",
    label: "Cancel booking",
    method: "POST",
    path: "/cargo-api/v1/bookings/cancel",
    description: "Cancel a booking and return the AWB to GSA, agent, or airline.",
    bodyExample: { awbNo: "16012345678", returnAwbTo: "GSA" },
    destructive: true,
  },
  {
    id: "bookings-update",
    group: "Bookings",
    label: "Update booking",
    method: "PATCH",
    path: "/cargo-api/v1/bookings/update",
    description: "Update an existing booking by AWB number.",
    bodyExample: { awbNo: "16012345678", grossweight: 120, chargeweight: 120, pieces: 6, flight: "SV1234", flightDate: "2026-06-01" },
  },
  {
    id: "bookings-search",
    group: "Bookings",
    label: "Search bookings",
    method: "GET",
    path: "/cargo-api/v1/bookings/search",
    description: "Search bookings by AWB, route, flight, date, agent, airline, product, or IATA number.",
    queryExample: { awbNo: "", origin: "FRA", destination: "JED", flightFromDate: "2026-06-01", flightToDate: "2026-06-30", iataNo: "12345678901" },
  },
  {
    id: "flights-find-routes",
    group: "Flights",
    label: "Find routes",
    method: "POST",
    path: "/cargo-api/v1/flights/find-routes",
    description: "Find available routes between airports and carriers.",
    bodyExample: { carrierCode: "SV", origin: "FRA", destination: "JED" },
  },
  {
    id: "flights-generate-fbl",
    group: "Flights",
    label: "Generate FBL",
    method: "POST",
    path: "/cargo-api/v1/flights/generate-fbl",
    description: "Generate Freight Booked List for a flight and date.",
    bodyExample: { flight: "SV1234", flightDate: "14/06/2026" },
  },
  {
    id: "tracking-awb-list",
    group: "Tracking",
    label: "Track AWB list",
    method: "POST",
    path: "/cargo-api/v1/tracking/awb-list",
    description: "Track multiple airwaybills.",
    bodyExample: { awbNos: ["16012345678", "16012345679"] },
  },
  {
    id: "tracking-awb",
    group: "Tracking",
    label: "Track one AWB",
    method: "GET",
    path: "/cargo-api/v1/tracking/{awbno}",
    description: "Find shipment details by AWB number.",
    pathParams: ["awbno"],
  },
  {
    id: "tracking-awb-list-legacy",
    group: "Tracking",
    label: "Track AWB list (legacy)",
    method: "POST",
    path: "/cargo-api/tracking/byAirwaybillNos",
    description: "Track multiple airwaybills through the legacy shipment tracker endpoint.",
    bodyExample: { awbNos: ["16012345678", "16012345679"] },
  },
  {
    id: "tracking-awb-legacy",
    group: "Tracking",
    label: "Track one AWB (legacy)",
    method: "GET",
    path: "/cargo-api/tracking/{awbno}",
    description: "Find shipment details by AWB number through the legacy shipment tracker endpoint.",
    pathParams: ["awbno"],
  },
  {
    id: "shipments-search-awb",
    group: "Shipments",
    label: "Search AWB shipments",
    method: "POST",
    path: "/cargo-api/v1/shipments/search-awb",
    description: "Search export shipments by AWB, route, flight, date, status, or allotment.",
    bodyExample: { origin: "FRA", destination: "JED", flightFrom: "2026-06-01", flightTo: "2026-06-30", archivedAirwaybills: false },
  },
  {
    id: "shipments-create-awb",
    group: "Shipments",
    label: "Create export AWB",
    method: "POST",
    path: "/cargo-api/v1/shipments/create-awb",
    description: "Create an export shipment AWB.",
    bodyExample: {
      awbNo: "16012345678",
      origin: "FRA",
      destination: "JED",
      shipperName: "Example Shipper GmbH",
      agentName: "DHL Germany GmbH",
      description: "General cargo",
      pieces: 10,
      grossWeight: 250,
      chargeableWeight: 250,
    },
  },
  {
    id: "shipments-update-awb",
    group: "Shipments",
    label: "Update export AWB",
    method: "POST",
    path: "/cargo-api/v1/shipments/update-awb",
    description: "Update export shipment AWB fields.",
    bodyExample: { awbNo: "16012345678", shipperName: "Example Shipper GmbH", agentName: "DHL Germany GmbH", remarks: "Updated in AirGSA" },
  },
  {
    id: "rates-find-rates",
    group: "Rates",
    label: "Find rates",
    method: "POST",
    path: "/cargo-api/v1/rates/find-rates",
    description: "Find rates and calculate chargeable weight from gross weight and optional dimensions.",
    bodyExample: { carrierCode: "SV", origin: "FRA", destination: "JED", productType: "General", grossWeight: 250.5, chargeWeight: 250.5, flightDate: "2026-06-01" },
  },
  {
    id: "awb-stock-search",
    group: "AWB Stock",
    label: "Search AWB stock",
    method: "GET",
    path: "/cargo-api/awbstock/search-awb-stock",
    description: "Search AWB stock by airline code and IATA number.",
    queryExample: { airlineCode: "SV", iataNo: "12345678901" },
  },
  {
    id: "docmesh-process-v1",
    group: "DocMesh",
    label: "Process DocMesh",
    method: "POST",
    path: "/cargo-api/v1/docmesh/process-docmesh",
    description: "Process document data through DocMesh.",
    bodyExample: { fileName: "awb.pdf", extractedDocumentType: "AWB", status: "NEW", metadata: [] },
  },
  {
    id: "docmesh-process",
    group: "DocMesh",
    label: "Process DocMesh (legacy)",
    method: "POST",
    path: "/cargo-api/docmesh/process-docmesh",
    description: "Process document data through the legacy DocMesh endpoint.",
    bodyExample: { fileName: "awb.pdf", extractedDocumentType: "AWB", status: "NEW", metadata: [] },
  },
  {
    id: "docmesh-latest-flight-logs",
    group: "DocMesh",
    label: "Latest flight logs",
    method: "POST",
    path: "/cargo-api/docmesh/Latest-Flight-Logs",
    description: "Get latest flight logs from DocMesh.",
    bodyExample: {},
  },
  {
    id: "platform-rate-and-routes",
    group: "Platform API",
    label: "Platform rates and routes",
    method: "POST",
    path: "/cargo-api/platform/rate-and-routes",
    description: "Return rates and routes for platform integrations.",
    bodyExample: { origin: "FRA", destination: "JED", pieces: 10, grosswt: 250, agentName: "DHL Germany GmbH", iataNo: "12345678901" },
  },
  {
    id: "platform-request-quote",
    group: "Platform API",
    label: "Platform request quote",
    method: "POST",
    path: "/cargo-api/platform/request-quote",
    description: "Request a quote through platform integration.",
    bodyExample: { origin: "FRA", destination: "JED", pieces: 10, grosswt: 250, agentName: "DHL Germany GmbH", iataNo: "12345678901" },
  },
  {
    id: "platform-request-booking",
    group: "Platform API",
    label: "Platform request booking",
    method: "POST",
    path: "/cargo-api/platform/request-booking",
    description: "Request a booking through platform integration.",
    bodyExample: { origin: "FRA", destination: "JED", pieces: 10, grosswt: 250, agentName: "DHL Germany GmbH", iataNo: "12345678901" },
  },
  {
    id: "platform-update-booking",
    group: "Platform API",
    label: "Platform update booking",
    method: "PUT",
    path: "/cargo-api/platform/update-booking",
    description: "Update platform booking details.",
    bodyExample: { awbno: "16012345678", pieces: 10, grosswt: 250 },
  },
  {
    id: "platform-cancel-booking-or-quote",
    group: "Platform API",
    label: "Platform cancel booking/quote",
    method: "DELETE",
    path: "/cargo-api/platform/cancel-booking-or-quote",
    description: "Cancel a platform booking or quote.",
    bodyExample: { awbno: "16012345678" },
    destructive: true,
  },
  {
    id: "webcargo-rate-and-routes",
    group: "WebCargo Booking API",
    label: "WebCargo rates and routes",
    method: "POST",
    path: "/cargo-api/booking/rate-and-routes",
    description: "Return rates, routes, and charges.",
    bodyExample: {
      agentName: "Example Forwarder Ltd",
      iataNo: "12345678901",
      origin: "FRA",
      destination: "MIA",
      pieces: 10,
      grosswt: 1000,
      shc: "GCR",
      stackable: "N",
      productType: "GCR",
      dims: [
        {
          pieces: 10,
          len: 10,
          width: 10,
          height: 10,
          volume: 100,
          grossWeight: 1000,
          chargeWeight: 1000,
        },
      ],
      description: "GENERAL CARGO",
      cargoScreened: "Y",
      lengthUnit: "CM",
      weightUnit: "KG",
      fltFromDate: "2026-05-19",
      fltToDate: "2026-05-20",
    },
  },
  {
    id: "webcargo-request-quote",
    group: "WebCargo Booking API",
    label: "WebCargo request quote",
    method: "POST",
    path: "/cargo-api/booking/request-quote",
    description: "Request a quote.",
    bodyExample: { agentName: "DHL Germany GmbH", iataNo: "123456789", origin: "FRA", destination: "JED", pieces: 10, grosswt: 250, airline: "SV", currency: "EUR" },
  },
  {
    id: "webcargo-request-booking",
    group: "WebCargo Booking API",
    label: "WebCargo request booking",
    method: "POST",
    path: "/cargo-api/booking/request-booking",
    description: "Request a booking.",
    bodyExample: {
      correlationId: "baf71333-d9b2-426b-b534-d375314978be",
      routingId: 1,
    },
  },
  {
    id: "webcargo-update-booking",
    group: "WebCargo Booking API",
    label: "WebCargo update booking",
    method: "PUT",
    path: "/cargo-api/booking/update-booking",
    description: "Update booking shipment details.",
    bodyExample: { awbno: "16012345678", pieces: 10, grosswt: 250 },
  },
  {
    id: "webcargo-list-booking",
    group: "WebCargo Booking API",
    label: "WebCargo list bookings",
    method: "GET",
    path: "/cargo-api/booking/list-booking",
    description: "List bookings by IATA number.",
    queryExample: { iataNo: "123456789" },
  },
  {
    id: "webcargo-cancel-booking-or-quote",
    group: "WebCargo Booking API",
    label: "WebCargo cancel booking/quote",
    method: "DELETE",
    path: "/cargo-api/booking/cancel-booking-or-quote",
    description: "Cancel a booking or quote.",
    bodyExample: { awbno: "16012345678" },
    destructive: true,
  },
];

export function getEcargowareOperation(id: string) {
  return ECARGOWARE_OPERATIONS.find((operation) => operation.id === id) ?? null;
}

export function getEcargowareGroups() {
  return Array.from(new Set(ECARGOWARE_OPERATIONS.map((operation) => operation.group)));
}
